baseURL = 'https://wenling91.github.io/Kpop_Encyclopedia/'
languageCode = 'zh-tw'
title = 'KPOP ç™¾ç§‘å…¨æ›¸'
theme = "PaperMod"

[params.homeInfoParams]
Title = "æ­¡è¿ä¾†åˆ° KPOP ç™¾ç§‘å…¨æ›¸ğŸ‘‹"
Content = """
æœ¬ç¶²ç«™ç‚ºå€‹äººæ•´ç†ä¹‹ K-POP åœ˜é«”è³‡æ–™åº«ï¼Œä½œç‚ºè¨˜éŒ„èˆ‡æŸ¥è©¢ç”¨é€”ã€‚\n
è³‡æ–™ä¸»è¦å½™æ•´è‡ªç¶­åŸºç™¾ç§‘ç­‰å…¬é–‹ä¾†æºã€‚\n
å¦‚æœ‰è³‡æ–™éŒ¯èª¤æˆ–éºæ¼ï¼Œæ­¡è¿æŒ‡æ­£ã€‚\n
"""

[[params.socialIcons]]
name = "email"
url = "ce574357@gmail.com"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/wen0__"

[menu]
  [[menu.main]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 2
    name = "KPOP"
    url = "/kpop/"