baseURL = 'https://wenling91.github.io/Kpop_Encyclopedia/'
languageCode = 'zh-tw'
title = 'KPOP ç™¾ç§‘å…¨æ›¸'
theme = "PaperMod"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mainSections = ["posts", "blog"]  # ä¸åŒ…å« kpop

[params.homeInfoParams]
Title = "æ­¡è¿ä¾†åˆ° KPOP ç™¾ç§‘å…¨æ›¸ğŸ‘‹"
Content = """
- æœ¬ç¶²ç«™ç‚ºå€‹äººæ•´ç†ä¹‹ K-POP åœ˜é«”è³‡æ–™åº«ï¼Œä½œç‚ºè¨˜éŒ„èˆ‡æŸ¥è©¢ç”¨é€”ã€‚
- è³‡æ–™ä¸»è¦å½™æ•´è‡ªç¶­åŸºç™¾ç§‘ç­‰å…¬é–‹ä¾†æºã€‚
- å¦‚æœ‰è³‡æ–™éŒ¯èª¤æˆ–éºæ¼ï¼Œæ­¡è¿æŒ‡æ­£ã€‚
"""

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/wen0__"

[menu]
  [[menu.main]]
    name = "é¦–é "
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "åœ˜é«”åˆ—è¡¨"
    identifier = "kpop"
    url = "/kpop/"
    weight = 2
  [[menu.main]]
    name = "å•é¡Œå›å ±"
    identifier = "report"
    url = "/report/"
    weight = 3
